# Generated by Django 3.2.5 on 2021-07-17 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_path', models.CharField(blank=True, max_length=255, verbose_name='出版社')),
                ('success', models.CharField(blank=True, max_length=255, verbose_name='成功')),
                ('message', models.CharField(blank=True, max_length=255, verbose_name='メッセージ')),
                ('field_class', models.IntegerField(db_column='class', verbose_name='クラス')),
                ('confidence', models.DecimalField(decimal_places=4, max_digits=5, verbose_name='信頼性')),
                ('request_timestamp', models.PositiveIntegerField(verbose_name='リクエスト時刻')),
                ('response_timestamp', models.PositiveIntegerField(verbose_name='レスポンス時刻')),
            ],
        ),
    ]
