# Generated by Django 3.2.5 on 2021-07-17 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysislog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysislog',
            name='confidence',
            field=models.DecimalField(decimal_places=4, max_digits=5, null=True, verbose_name='信頼性'),
        ),
        migrations.AlterField(
            model_name='analysislog',
            name='field_class',
            field=models.IntegerField(db_column='class', null=True, verbose_name='クラス'),
        ),
        migrations.AlterField(
            model_name='analysislog',
            name='image_path',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='出版社'),
        ),
        migrations.AlterField(
            model_name='analysislog',
            name='message',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='メッセージ'),
        ),
        migrations.AlterField(
            model_name='analysislog',
            name='request_timestamp',
            field=models.PositiveIntegerField(null=True, verbose_name='リクエスト時刻'),
        ),
        migrations.AlterField(
            model_name='analysislog',
            name='response_timestamp',
            field=models.PositiveIntegerField(null=True, verbose_name='レスポンス時刻'),
        ),
        migrations.AlterField(
            model_name='analysislog',
            name='success',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='成功'),
        ),
    ]
