# Generated by Django 3.2.5 on 2021-07-17 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysislog', '0005_alter_analysislog_success'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysislog',
            name='success',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='成功'),
        ),
    ]
