# Generated by Django 3.2.5 on 2021-07-17 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysislog', '0006_alter_analysislog_success'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='analysislog',
            table='ai_analysis_log',
        ),
    ]
